"""
LLM Labeling Script.

This script loads the topics generated by the BERTopic model and utilizes
a local Llama 3.1 LLM to automatically generate concise and descriptive
labels for each topic based on its keywords and representative docs.
"""

# Thridy-Party Imports
import pandas as pd
from llama_cpp import Llama

# -----------------------------------------------------------------------------
# Configuration & Constants
# -----------------------------------------------------------------------------
LLAMA_MODEL_PATH = 'models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf'

# System prompt for topic labeling
LLAMA_PROMPT_TEMPLATE = """<|start_header_id|>system<|end_header_id|>

Você é um especialista em análise de feedback educacional.
Sua tarefa é sintetizar um tópico de comentários em um ÚNICO RÓTULO curto e descritivo.

DIRETRIZES:
1. Analise as Palavras-Chave e os Comentários.
2. Formato: Detalhe Específico.
3. NÃO explique. NÃO use frases introdutórias.
4. No rótulo, NÃO USE termos genéricos. Seja específico.
5. Deixe explícito a polaridade do sentimento no rótulo.
6. Se houver nome próprio nas Palavras-chave ou nos Comentários, NÃO o utilize
no rótulo.
7. NÃO use mais de 7 palavras no rótulo.

<|eot_id|><|start_header_id|>user<|end_header_id|>

Analise e gere o rótulo para este grupo:
Palavras-Chave: "{keywords_str}"
Comentários: "{docs_str}"

Rótulo: """


def run_labeling() -> None:
    """
    Main function to execute the automatic LLM labeling over BERTopic clusters.
    """
    # Load previously generated BERTopic topics
    df_bertopic = pd.read_pickle('src/data/df_bertopic_topics.pkl')

    # Initialize the local Llama model
    llama_model = Llama(
        model_path=LLAMA_MODEL_PATH,
        n_ctx=4096,
        n_threads=11,
        verbose=False
    )

    # Get keywords and docs from each BERTopic topic
    for topic_idx, row in enumerate(df_bertopic.itertuples()):
        keywords_list = row[1]
        docs_list = row[2]

        # Convert lists to strings for prompt formatting
        keywords_str = ", ".join(keywords_list)
        docs_str = " | ".join(docs_list)

        # Format the final prompt with current topic data
        final_prompt = LLAMA_PROMPT_TEMPLATE.format(
            docs_str=docs_str,
            keywords_str=keywords_str
        )

        # Run inference using the LLM setup for extraction
        output = llama_model(
            final_prompt,
            max_tokens=50,
            stop=["<|eot_id|>", "Exemplos:"],
            temperature=0.1,
            top_p=0.7,
            echo=False
        )

        # Extract only the completion generated by the model
        resposta = output['choices'][0]['text'].strip()

        # Log labeled results
        print("-" * 30)
        print(f"RÓTULO {topic_idx}: {resposta}")
        print(f'Palavras-chaves: {keywords_list}')
        print("-" * 30)

    print("\n✅ LLM labeling execution completed successfully!\n")

if __name__ == "__main__":
    run_labeling()
