"""
LLM Labeling Script.

This script loads the topics generated by the BERTopic model and utilizes
a local Qwen 2.5 LLM to automatically generate concise and descriptive
labels for each topic based on its keywords and representative docs.
"""

# Thridy-Party Imports
import pandas as pd
from llama_cpp import Llama

# -----------------------------------------------------------------------------
# Configuration & Constants
# -----------------------------------------------------------------------------
QWEN_MODEL_PATH = 'model/Qwen2.5-7B-Instruct-Q4_K_M.gguf'

# System prompt for topic labeling
QWEN_PROMPT_TEMPLATE = """<|im_start|>system
Você é um especialista em análise de feedback educacional.
Sua tarefa é sintetizar um tópico de comentários em um ÚNICO RÓTULO curto e descritivo.

DIRETRIZES:
1. Analise as Palavras-Chave e os Comentários.
2. Formato: Detalhe Específico.
3. NÃO explique. NÃO use frases introdutórias.
4. No rótulo, NÃO USE termos genéricos. Seja específico.
5. Deixe explícito a polaridade do sentimento no rótulo.
6. Se houver nome próprio nas Palavras-chave ou nos Comentários, NÃO o utilize no rótulo.
7. NÃO use mais de 7 palavras no rótulo.<|im_end|>
<|im_start|>user
Analise e gere o rótulo para este grupo:
Palavras-Chave: "{keywords_str}"
Comentários: "{docs_str}"

Rótulo:<|im_end|>
<|im_start|>assistant
"""


# English translation of the prompt used above 

# """<|im_start|>system
# You are an expert in educational feedback analysis.
# Your task is to synthesize a topic from comments into a SINGLE short and descriptive LABEL.
#
# GUIDELINES:
# 1. Analyze the Keywords and Comments.
# 2. Format: Specific Detail.
# 3. Do NOT explain. Do NOT use introductory phrases.
# 4. In the label, do NOT USE generic terms. Be specific.
# 5. Make the sentiment polarity explicit in the label.
# 6. If there is a proper name in the Keywords or Comments, do NOT use it in the label.
# 7. Do NOT use more than 7 words in the label.<|im_end|>
# <|im_start|>user
# Analyze and generate the label for this group:
# Keywords: "{keywords_str}"
# Comments: "{docs_str}"
#
# Label:<|im_end|>
# <|im_start|>assistant
# """


def run_labeling() -> None:
    """
    Main function to execute the automatic LLM labeling over BERTopic clusters.
    """
    # Load previously generated BERTopic topics
    df_bertopic = pd.read_pickle('src/tmp/df_bertopic_topics.pkl')

    labels = []

    # Initialize the local Qwen model
    qwen_model = Llama(
        model_path=QWEN_MODEL_PATH,
        n_ctx=4096,
        n_threads=11,
        verbose=False
    )

    # Get keywords and docs from each BERTopic topic
    for topic_idx, row in enumerate(df_bertopic.itertuples()):
        keywords_list = row[1]
        docs_list = row[2]

        print(f'topic: {keywords_list}\n\ndocs: {docs_list}\n======\n\n')

        # Convert lists to strings for prompt formatting
        keywords_str = ", ".join(keywords_list)
        docs_str = " | ".join(docs_list)

        # Format the final prompt with current topic data
        final_prompt = QWEN_PROMPT_TEMPLATE.format(
            docs_str=docs_str,
            keywords_str=keywords_str
        )

        # Run inference using the LLM setup for extraction
        output = qwen_model(
            final_prompt,
            max_tokens=50,
            stop=["<|im_end|>", "Exemplos:"],
            temperature=0.1,
            top_p=0.9,
            echo=False
        )

        # Extract only the completion generated by the model
        label = output['choices'][0]['text'].strip()
        labels.append(label)

        # Log labeled results
        print("-" * 30)
        print(f"Label {topic_idx}: {label}")
        print(f'Keywords: {keywords_list}')
        print("-" * 30)

    # Add generated labels to dataframe
    df_bertopic['llm_label'] = labels
    
    # Save to a CSV file containing only the requested columns
    df_bertopic[['llm_label', 'keywords']].to_csv('src/tmp/bertopic_qwen_labels.csv', index=False, encoding='utf-8-sig')

    print("\n✅ LLM labeling execution completed successfully and saved to CSV!\n")

if __name__ == "__main__":
    run_labeling()
